### ISSUE TITLE
Removed all my projects

### ISSUE THREAD

**Issue by razbakov** [Learnosity/vagrant-nfs_guest#15]
I already had Vagrantfile and I changed `nfs` to `nfs_guest` and it removed all my projects. 
You should add **WARNING** to readme file

**Comment by alangarf** [comment]
It's just mounted on top of the directory your existing stuff is in on the host. Stop the Vagrant VM and it'll unmount the share and the data will be there. It doesn't delete anything. Just move the mount.

**Comment by rozagh** [comment]
My mounted directory is the same as where we define the vagrant, after reloading the vm all the files are gone and now I cannot access the VM either to stop it

**Comment by alangarf** [comment]
The files are on the host. The plugin works on the files being on the guest.

Because you've enabled the plugin using the same directory as your files it has just "mounted" the guest directory on top of the host directory. The files are all still there, but inaccessibe because they've been "shadowed" by the NFS mount.

`vagrant halt` will stop the VM. Or even opening Virtual Box console and stopping the VM. Once stopped the files will reappear. Choose another mount directory, or move the files out of the directory before you start the VM.
