### ISSUE TITLE
Plugin does not work on Ubuntu if firewall is enabled

### ISSUE THREAD

**Issue by IvanChepurnyi** [Learnosity/vagrant-nfs_guest#26]
In case if Ubuntu Firewall is enabled, then the plugin will fail to execute NFS mount.

It is possible to make a workaround via Vagrant provisioner, by disabling Ubuntu firewall over there, but in this case, the mount will work only on the next boot.

The correct solution would be to add `ufw disable` over here, right after installing nfs server:
https://github.com/Learnosity/vagrant-nfs_guest/blob/master/lib/vagrant-nfs_guest/guests/ubuntu/cap/nfs_server.rb#L8

Maybe disabling firewall completely is also a bad idea, but then you need to make RPC ports being fixed for NFS and add a rule to the firewall for the host machine.

**Comment by alangarf** [comment]
Thanks for the input, Ubuntu by default doesn't turn the firewall on. Because of this I'd rather not have the plugin muck around with the firewall settings if they have been altered from the default. If you turn on the firewall, it's up to you then to manage the rules I guess. I probably should add some comment to the docs to state that.
