### ISSUE TITLE
1.0.3 doesn't work on CentOS/7

### ISSUE THREAD

**Issue by dnsl48** [Learnosity/vagrant-nfs_guest#57]
#52 was merged into master 2 months ago, but there's no 1.0.4 release yet.
Are there plans to release 1.0.4 any time soon?

**Comment by alangarf** [comment]
Yes, I'm working on a new version. The issue is we have diverging tech in "RedHat" at the moment with CentOS/7 having systemd and yum, Fedora having systemd and dnf, RHEL having a mix of both.

Just trying to test all the variations and make them all work happy etc is proving time consuming which is why I've not gotten around to it with my usual busy days.

It will be soon. Cheers!

**Comment by dnsl48** [comment]
Thank you, awesome work you are doing :)
If someone else finds this issue in the meantime, I just downgraded the version to `1.0.0`, which seems to be working well with `CentOS/7`

**Comment by mhitza** [comment]
Could we get a new version for the plugin?

**Comment by alangarf** [comment]
Fixed. Thanks.
